apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  namespace: default
  labels:
    app: test-app
  annotations:
    deployment.kubernetes.io/revision: "2"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: tomcat
        image: 876724398547.dkr.ecr.us-west-2.amazonaws.com/prasad-assignment-9:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
  - name: port8080
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32343
